// internal/data/models/diagnosis.go
package models

import (
	"time"

	"github.com/google/uuid"
)

// Diagnosis represents a *preliminary* diagnosis generated by the AI system.
type Diagnosis struct {
	ID            uuid.UUID `json:"id" db:"id"`
	ResultID      uuid.UUID `json:"result_id" db:"result_id"`   // Corrected: Added ResultID, removed PatientID
	SessionID     uuid.UUID `json:"session_id" db:"session_id"` // Corrected: Added SessionID, removed PatientID
	DiagnosisText string    `json:"diagnosis_text" db:"diagnosis_text"`
	Confidence    string    `json:"confidence" db:"confidence"`
	Justification string    `json:"justification" db:"justification"`
	CreatedAt     time.Time `json:"created_at" db:"created_at"`
	UpdatedAt     time.Time `json:"updated_at" db:"updated_at"`
}
