// internal/data/models/stage.go
package models

import (
	"time"

	"github.com/google/uuid"
)

// Stage represents *preliminary* staging information generated by the AI system.
type Stage struct {
	ID          uuid.UUID `json:"id" db:"id"`
	ResultID    uuid.UUID `json:"result_id" db:"result_id"`   // Corrected: Added ResultID, removed PatientID
	SessionID   uuid.UUID `json:"session_id" db:"session_id"` // Corrected: Added SessionID, removed PatientID
	T           string    `json:"T" db:"t"`
	N           string    `json:"N" db:"n"`
	M           string    `json:"M" db:"m"`
	Confidence  string    `json:"confidence" db:"confidence"`
	Explanation string    `json:"explanation" db:"explanation"` // Added Explanation field - Recommendation 6
	CreatedAt   time.Time `json:"created_at" db:"created_at"`
	UpdatedAt   time.Time `json:"updated_at" db:"updated_at"`
}
