package entities

import "github.com/google/uuid"

// Diagnosis represents a *preliminary* diagnosis generated by the AI system.
// It is crucial to emphasize that this is *not* a definitive diagnosis and
// *must* be confirmed by a qualified physician.
type Diagnosis struct {
	BaseEntity
	SessionID     uuid.UUID `json:"session_id,omitempty"`
	DiagnosisText string    `json:"diagnosis_text,omitempty"` // Preliminary diagnosis (plain language).
	Confidence    string    `json:"confidence,omitempty"`     // e.g., "Low", "Moderate", "High".
	Justification string    `json:"justification,omitempty"`  // Explanation (plain language).
}
