package entities

import "github.com/google/uuid"

// Stage represents *preliminary* staging information generated by the AI system.
// This is *not* definitive staging and *must* be confirmed by a qualified physician.
type Stage struct {
	BaseEntity
	SessionID  uuid.UUID `json:"session_id,omitempty"`
	T          string    `json:"T,omitempty"`          // T component of TNM.
	N          string    `json:"N,omitempty"`          // N component of TNM.
	M          string    `json:"M,omitempty"`          // M component of TNM.
	Confidence string    `json:"confidence,omitempty"` // Confidence in the preliminary staging.
}
